[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[context.production.environment]
  API_BASE_URL = "https://api.voiceai.example.com"
  VITE_API_BASE_URL = "https://api.voiceai.example.com"

[context.develop.environment]
  API_BASE_URL = "https://dev.api.voiceai.example.com"
  VITE_API_BASE_URL = "https://dev.api.voiceai.example.com"

[context.deploy-preview.environment]
  API_BASE_URL = "https://staging.api.voiceai.example.com"
  VITE_API_BASE_URL = "https://staging.api.voiceai.example.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"