global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files to load
rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'voiceai-api'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['api.voiceai.com:9090']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: voiceai-api
    tls_config:
      insecure_skip_verify: false
    basic_auth:
      username: ${PROMETHEUS_USER}
      password: ${PROMETHEUS_PASSWORD}

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter.voiceai.com:9100']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scheme: http

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scheme: http

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'