[build]
  base = "admin-dashboard/"
  command = "npm ci && npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.api.your-domain.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  framework = "react"
  targetPort = 3000
  port = 8888
  command = "npm run dev"