steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/voiceai-service', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/voiceai-service']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'voiceai-service',
         '--image', 'gcr.io/$PROJECT_ID/voiceai-service',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/voiceai-service'