apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: voiceai-server
  annotations:
    run.googleapis.com/cpu-throttling: "false"
    run.googleapis.com/startup-cpu-boost: "true"
    run.googleapis.com/cloudsql-instances: "${PROJECT_ID}:${REGION}:${INSTANCE_NAME}"
    autoscaling.knative.dev/minScale: "1"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/targetUtilizationPercentage: "70"
        run.googleapis.com/execution-environment: "gen2"
        run.googleapis.com/vpc-access-connector: "vpc-connector"
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/${PROJECT_ID}/voiceai-server
        ports:
          - name: http1
            containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 3
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "8080"
          - name: DEEPGRAM_API_KEY
            valueFrom:
              secretKeyRef:
                name: voiceai-secrets
                key: deepgram-key
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: voiceai-secrets
                key: database-url
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: voiceai-secrets
                key: redis-url