# .github/workflows/deploy-render.yml
name: Deploy to Render
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t render-voice-agent:${{ github.sha }} .
      - run: docker tag render-voice-agent:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/voice-agent:${{ github.sha }}
      - run: docker push ${{ secrets.REGISTRY_URL }}/voice-agent:${{ github.sha }}